=== EiNirvana/Llenguatge-de-marques/Pràctica 6/practica6.dtd
<!ELEMENT tienda_camisetas (clientes, stock_tienda, nombre, direccion, horario, telefono)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT direccion (#PCDATA)>
    <!ELEMENT horario (#PCDATA)>
    <!ELEMENT telefono (#PCDATA)>
    <!ELEMENT clientes (cliente*)>
    <!ELEMENT stock_tienda (camisetas_manga_corta, camisetas_manga_larga, sudaderas)>
        <!ELEMENT cliente (nombre, apellido, metodo_pago, direccion_facturacion, direccion_envio, productos_fav*)>
        <!ELEMENT camisetas_manga_corta (camiseta_manga_corta*)>
        <!ELEMENT camisetas_manga_larga (camiseta_manga_larga*)>
        <!ELEMENT sudaderas (sudadera*)>
            <!--<!ELEMENT nombre (#PCDATA)>-->
            <!ELEMENT apellido (#PCDATA)>
            <!ELEMENT metodo_pago (#PCDATA)>
            <!ELEMENT direccion_facturacion (#PCDATA)>
            <!ELEMENT direccion_envio (#PCDATA)>
            <!ELEMENT productos_fav (nombre_producto*)>
            <!ELEMENT camiseta_manga_corta (tematica, titulo?, talla_disponible+, img, color, material, price, codi)> 
            <!ELEMENT camiseta_manga_larga (tematica, titulo?, talla_disponible+, img, color, material, price, codi)>
            <!ELEMENT sudadera (tematica, titulo, talla_disponible+, img, color, material, price, codi)>
                <!ELEMENT tematica (#PCDATA)>
                <!ELEMENT talla_disponible (S, M, L, XL)>
                <!ELEMENT material (#PCDATA)> 
                <!ELEMENT color (#PCDATA)> 
                <!ELEMENT price (#PCDATA)>
                <!ELEMENT nombre_producto (#PCDATA)>
                <!ELEMENT img ANY>
                <!ELEMENT codi ANY>
                <!ATTLIST direccion_envio via CDATA #REQUIRED>
                <!ATTLIST direccion_facturacion via CDATA #REQUIRED>
                <!ATTLIST titulo lang (en | ca) #REQUIRED>
                <!ATTLIST codi id ID #REQUIRED>
                <!ATTLIST img url CDATA #REQUIRED>
                <!ATTLIST nombre_producto ref IDREF NCName #REQUIRED> 
                    <!ELEMENT S (#PCDATA)> 
                    <!ELEMENT M (#PCDATA)> 
                    <!ELEMENT L (#PCDATA)> 
                    <!ELEMENT XL (#PCDATA)>

=== EiNirvana/Llenguatge-de-marques/Pràctica 6/practica5_modificat_per_julivert.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tienda_camisetas SYSTEM "practica6.dtd">
<tienda_camisetas>
	<nombre>Pamplinas sponsor t-shirts</nombre>
	<direccion>C/inventada nº</direccion>
	<horario>15:00 a 19:00</horario>
	<telefono>000 000 000</telefono>
	<clientes>
	    <cliente>
	        <nombre>Paco</nombre>
            <apellido>XD</apellido>
	        <metodo_pago>Efectivo</metodo_pago>
	        <direccion_facturacion via="calle"> Nolose nº </direccion_facturacion>
	        <direccion_envio via="paseo"> Nolose2 nº </direccion_envio>
	        <productos_fav>
	            <nombre_producto ref="008">HO HO Nelson</nombre_producto>
                <nombre_producto ref="009">Goku</nombre_producto>
                <nombre_producto ref="010">Naruto</nombre_producto>
            </productos_fav>
        </cliente>
	    <cliente>
            <nombre>Paco</nombre>
            <apellido>XD2</apellido>
	        <metodo_pago>Tarjeta</metodo_pago>
	        <direccion_facturacion via="calle"> Nolose3 nº</direccion_facturacion>
	        <direccion_envio via="avenida"> Nolose4 nº</direccion_envio>
	        <productos_fav>
	            <nombre_producto ref="011">HO HO Nelson 2.0</nombre_producto>
                <nombre_producto ref="012">One piece</nombre_producto>
                <nombre_producto ref="013">LOL</nombre_producto>
            </productos_fav>
        </cliente>
    </clientes>
    <stock_tienda>
        <camisetas_manga_corta>
            <camiseta_manga_corta>
	            <tematica>Anime</tematica>
		        <titulo lang="en">DBZ</titulo>
                <codi id="006"></codi>
		        <talla_disponible>
		            <S>20</S>
                    <M>30</M>
                    <L>40</L>
                    <XL>16</XL>
                </talla_disponible>
		        <img url="url/ejemplo.jpg"/>
                <color>naranja</color>
			    <material>algodón</material>
			    <price>20.00</price>
 		    </camiseta_manga_corta>
            <camiseta_manga_corta>
                <tematica>Futbol</tematica>
                <titulo lang="ca">FCB</titulo>
                <codi id="007"></codi>
                <talla_disponible>
                    <S>88</S>
                    <M>11</M>
                    <L>42</L>
                    <XL>26</XL>
                </talla_disponible>
                <img url="url/ejemplo.jpg"/>
                <color>blaugrana</color>
                <material>algodón</material>
                <price>120.00</price>
            </camiseta_manga_corta>
        </camisetas_manga_corta>
        <camisetas_manga_larga>
            <camiseta_manga_larga>
                <tematica>navidad</tematica>
                <titulo lang="en">HO HO Nelson</titulo>
                <codi id="008"></codi>
                <!-- Todas las tallas disponibles de la tienda-->
                <talla_disponible>
                    <S>20</S>
                    <M>30</M>
                    <L>34</L>
                    <XL>16</XL>
                </talla_disponible>
                <material>algodón</material>
                <img url="url/ejemplo.jpg"/>
                <color>blaugrana</color>
                <price>300.00</price>
            </camiseta_manga_larga>
        </camisetas_manga_larga>
        <sudaderas>
            <sudadera>
                <tematica>anime</tematica>
                <titulo lang="en">One Piece</titulo>
                <codi id="009"></codi>
                <!-- Todas las tallas disponibles de la tienda-->
                <talla_disponible>
                    <S>22</S>
                    <M>34</M>
                    <L>65</L>
                    <XL>19</XL>
                </talla_disponible>
                <material>algodón</material>
                <img url="url/ejemplo.jpg"/>
                <color>rojo</color>
                <price>3002.00</price>  
            </sudadera>
        </sudaderas>	
    </stock_tienda>
</tienda_camisetas>
